name: food
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies:


  font_awesome_flutter: ^10.2.1
  im_stepper: ^1.0.1+1
  buttons_tabbar: ^1.3.6
  flutter_masked_text2: ^0.9.1
  flutter_otp_text_field: ^1.1.1
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  flutter_svg: ^1.1.5
  sliding_up_panel: ^2.0.0+1
  dropdown_button2: ^1.8.9
  validatorless: ^1.2.3
  flutter_rating_bar: ^4.0.1
  time_range: ^1.0.3
  another_stepper: ^1.0.4
  dotted_border: ^2.0.0+3
  intl: ^0.17.0
  get_cli: ^1.8.1
  get: 4.6.4
  favorite_button: ^0.0.4
  flutter_switch: ^0.3.2
  adaptive_action_sheet: ^2.0.2
  snapping_sheet: ^3.1.0
  modal_bottom_sheet: ^2.1.2
  expandable: ^5.0.1
  roundcheckbox: ^2.0.5

  flutter: 
    sdk: flutter


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  image_path: assets/icons/logo.png
  android: true
  ios: true

flutter: 
  assets: 
    - assets/
    - assets/icons/
    - assets/fonts/
  fonts: 
    - family: DMSans
      fonts: 
        - asset: assets/fonts/DMSans_Regular.ttf
  uses-material-design: true

