part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASHONE = _Paths.SPLASHONE;
  static const SPLASHTWO = _Paths.SPLASHTWO;
  static const ONBOARDING = _Paths.ONBOARDING;
  static const SIGNUPWITHPHONENUMBER = _Paths.SIGNUPWITHPHONENUMBER;
  static const OTPCODE = _Paths.OTPCODE;
  static const YOURNAME = _Paths.YOURNAME;
  static const ACCOUNTCOMPLETE = _Paths.ACCOUNTCOMPLETE;
  static const FORGOTPASSWORD = _Paths.FORGOTPASSWORD;
  static const RESET_PASSWORD = _Paths.RESET_PASSWORD;
  static const RESET_PASSWORD_WITH_PHONE = _Paths.RESET_PASSWORD_WITH_PHONE;
  static const OTP_NUMBER_FORGOT = _Paths.OTP_NUMBER_FORGOT;
  static const OTP_EMAIL_FORGOT = _Paths.OTP_EMAIL_FORGOT;
  static const CREATE_NEW_PASSWORD = _Paths.CREATE_NEW_PASSWORD;
  static const CONGRATS_PASSWORD_RESET = _Paths.CONGRATS_PASSWORD_RESET;
  static const BOTTOMBAR = _Paths.BOTTOMBAR;
  static const BROWSE = _Paths.BROWSE;
  static const CART = _Paths.CART;
  static const PROFILE = _Paths.PROFILE;
  static const FILTER = _Paths.FILTER;
  static const NEARBY_RESTAURANTS = _Paths.NEARBY_RESTAURANTS;
  static const RESTAURANT_DETAIL = _Paths.RESTAURANT_DETAIL;
  static const SIGNIN = _Paths.SIGNIN;
  static const PIN_LOCATION = _Paths.PIN_LOCATION;
  static const PIN_LOCATION_TWO = _Paths.PIN_LOCATION_TWO;
  static const PIN_LOCATION_THREE = _Paths.PIN_LOCATION_THREE;
  static const SEARCH_IT = _Paths.SEARCH_IT;
  static const CONFIRM_ORDER = _Paths.CONFIRM_ORDER;
  static const DELIVERY_OPTION = _Paths.DELIVERY_OPTION;
  static const PAYMENT_METHODS = _Paths.PAYMENT_METHODS;
  static const MASTER_CARD_DETAILS = _Paths.MASTER_CARD_DETAILS;
  static const ADD_PAYMENT = _Paths.ADD_PAYMENT;
  static const TIP_AND_NOTES = _Paths.TIP_AND_NOTES;
  static const CUSTOM_AMOUNT = _Paths.CUSTOM_AMOUNT;
  static const ALERT_BOX = _Paths.ALERT_BOX;
  static const TRACK_ORDER = _Paths.TRACK_ORDER;
  static const LIVE_TRACKING = _Paths.LIVE_TRACKING;
  static const ORDER_DETAILS = _Paths.ORDER_DETAILS;
  static const CONTACT_SUPPORT = _Paths.CONTACT_SUPPORT;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const PROMOTION = _Paths.PROMOTION;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASHONE = '/splashone';
  static const SPLASHTWO = '/splashtwo';
  static const ONBOARDING = '/onboarding';
  static const SIGNUPWITHPHONENUMBER = '/signupwithphonenumber';
  static const OTPCODE = '/otpcode';
  static const YOURNAME = '/yourname';
  static const ACCOUNTCOMPLETE = '/accountcomplete';
  static const FORGOTPASSWORD = '/forgotpassword';
  static const RESET_PASSWORD = '/reset-password';
  static const RESET_PASSWORD_WITH_PHONE = '/reset-password-with-phone';
  static const OTP_NUMBER_FORGOT = '/otp-number-forgot';
  static const OTP_EMAIL_FORGOT = '/otp-email-forgot';
  static const CREATE_NEW_PASSWORD = '/create-new-password';
  static const CONGRATS_PASSWORD_RESET = '/congrats-password-reset';
  static const BOTTOMBAR = '/bottombar';
  static const BROWSE = '/browse';
  static const CART = '/cart';
  static const PROFILE = '/profile';
  static const FILTER = '/filter';
  static const NEARBY_RESTAURANTS = '/nearby-restaurants';
  static const RESTAURANT_DETAIL = '/restaurant-detail';
  static const SIGNIN = '/signin';
  static const PIN_LOCATION = '/pin-location';
  static const PIN_LOCATION_TWO = '/pin-location-two';
  static const PIN_LOCATION_THREE = '/pin-location-three';
  static const SEARCH_IT = '/search-it';
  static const CONFIRM_ORDER = '/confirm-order';
  static const DELIVERY_OPTION = '/delivery-option';
  static const PAYMENT_METHODS = '/payment-methods';
  static const MASTER_CARD_DETAILS = '/master-card-details';
  static const ADD_PAYMENT = '/add-payment';
  static const TIP_AND_NOTES = '/tip-and-notes';
  static const CUSTOM_AMOUNT = '/custom-amount';
  static const ALERT_BOX = '/alert-box';
  static const TRACK_ORDER = '/track-order';
  static const LIVE_TRACKING = '/live-tracking';
  static const ORDER_DETAILS = '/order-details';
  static const CONTACT_SUPPORT = '/contact-support';
  static const NOTIFICATIONS = '/notifications';
  static const PROMOTION = '/promotion';
}
